config/routes.rb
class MobileConstraint
  def self.matches?(request)
    agent_str = request.user_agent.to_s.downcase
    (agent_str =~ Regexp.new(MOBILE_USER_AGENTS)) or request.subdomain == 'm'
  end
end

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # API
  # require 'dispatch'
  # mount Api::Dispatch => '/api'

  get '/jokes/video' => redirect('/')

  concern :sessionable do
    get :signup, to: 'users#new'
    post :signup, to: 'users#create'
    get :login, to: 'sessions#new'
    post :login, to: 'sessions#create'
    delete :logout, to: 'sessions#destroy'
    get :login_state, to: 'sessions#login_state'
  end

  concern :votable do
    post :up_vote
    post :down_vote
  end

  concern :jokeable do
    resources :jokes do
      concerns :votable
      resources :comments, shallow: true do
        concerns :votable
      end

      collection do
        get :hot
        get :shenhuifu
        get :qutu
        get :duanzi
        get :random
        get :search
        get :video
      end
    end
  end

  # 移动站的页面
  constraints(MobileConstraint) do
    scope module: 'mobile', as: :mobile do
      get '/jokes/video' => redirect('/')
      root to: 'jokes#index'
      concerns :jokeable
      concerns :sessionable
      resources :users
      resources :tags, only: [:index, :show]
    end
  end

  # 桌面站
  root 'jokes#index'

  # 第三方登录
  get 'auth/weibo/callback', to: 'auth#weibo_callback', as: :weibo_auth
  get 'auth/qq/callback', to: 'auth#qq_callback', as: :qq_auth

  # 瀑布流的单页
  get :hot, to: 'jokes#recommends', as: :recommends

  # 外链广告代码
  scope 'ad', as: 'ad' do
    get :recommends, to: 'ad#recommends'
    get 'pics', to: 'ad#pics', as: :pics
  end

  concerns :jokeable
  resources :users
  resources :tags, only: [:index, :show]
  concerns :sessionable

  namespace :settings do
    resource :password, only: [:show, :update]
    resource :profile, only: [:show, :update]
  end

  # 管理后台
  namespace :admin do
    root to: 'jokes#index'
    resources :jokes do
      collection do
        get :hot
        get :shenhuifu
        get :qutu
        get :duanzi
      end

      member do
        post :approve
        post :reject
        post :recommend
        post :unrecommend
      end
    end

    resources :tags do
      collection do
        get :search
      end
    end

    resources :users do
      member do
        post :block
        post :unblock
      end
    end
    resources :comments
    resources :websites
    resources :ads
  end
end

app/views/share/_bd_share.html.erb
<script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"<%= @joke.photos[0].url(:middle) rescue nil %>","bdStyle":"2","bdSize":"24"},"share":{},"image":{"viewList":["qzone","tsina","tqq","renren","weixin"],"viewText":"分享到","viewSize":"16"},"selectShare":{"bdContainerClass":null,"bdSelectMiniList":["qzone","tsina","tqq","renren","weixin"]}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script>

app/views/share/_comment_li.html.slim
li.clearfix
  .left
    .avatar.small
      a href="#{user_path(comment.user)}"
        = image_tag comment.user.avatar.url
      .nickname
        a href="#{user_path(comment.user)}" 
          span= comment.user.login
          span.text-muted= comment.created_at
        p= comment.body
  .right
    a.text-muted.reply 回复
    a.ding href="#"
      i.kx.kx-up-voted-sm
      small.text-muted= comment.up_votes_count
    span.text-muted 1楼
  - if comment.hot?
    i.kx.kx-light-up

app/views/share/_comments.html.slim
.box.load-comments
  .box-content
    .fast-comment
      .input-field.clearfix
        .left
          textarea.form-control placeholder="说点什么吧..."
          .limit
            span.size 0
            span.divider="/"
            span.total 140
        .left
          a.btn.btn-primary.postComment data-joke_id=joke.id 评论
      .error.text-danger 
    ul.text-list.comments 
      = render comments
    .text-muted.text-center.clearfix
      a href="#{joke_path(joke)}" 点击查看更多 → 
      a.right.text-muted 收起 ↑

app/views/share/_flash_message.html.slim
- [:success, :info, :warn, :danger, :error].each do |type|
  - if flash[type]
    .box-entend.flash-messages
      .flash-global.clearfix class="flash-#{type}"
        .flash-title 由于以下错误不能提交:
        p= flash[type]

app/views/share/_footer.html.slim
.footer
  .inner
    - if url_for == root_path
      .website
        h4 友情链接
        .links
          - Website.order('priority DESC, created_at ASC').each do |website|
            a href="#{website.url}" target="_blank"= website.name

    .text-center.announce 
      p 本站内容均来自互联网,本站不以营利为目的,这是一个注重分享交流的网站,为了建设健康向上的网络环境,请未满18周岁的少年在家长的陪同下观看。
      p 如果喜欢，请支持正版！若侵犯到您的权益，联系我们处理。    
    .copy-right.text-center.text-muted Copyright 2008-2018 开心100 www.kaixin100.com 版权所有 京ICP备11031391号-8

javascript:
  var _hmt = _hmt || [];
  (function() {
    var hm = document.createElement("script");
    hm.src = "//hm.baidu.com/hm.js?e3840f963bf7aa7b7fb51455cf965137";
    var s = document.getElementsByTagName("script")[0]; 
    s.parentNode.insertBefore(hm, s);
  })();

= render_current_user_as_json

app/views/share/_form_error.html.slim
- if target.errors.any?
  .box-entend.flash-messages
    .flash-global.flash-error.clearfix
      .flash-title 由于以下错误不能提交:
      ul
        - target.errors.full_messages.each do |message|
          li = message

app/views/share/_navbar.html.slim
ul
  li
    a.dropdown-toggle.active href="#" 热门
    .dropdown
  li
    a href='#' 神回复
  li
    a href='#' 趣图
  li
    a href='#' 视频
  li
    a href='#' 段子

app/views/share/_no_login.html.slim
.right.links
  .no-login
    a href="/auth/weibo" 微博登录
    a href="/auth/qq" QQ 
    a |
    a href="#{login_path}" 登录
    a.no-margin-right href="#{signup_path}" 注册  

app/views/share/_png_fix.html.erb
<!--[if lt IE 9]>
  <%= javascript_include_tag 'html5shiv.js' %>
<![endif]-->   
<!--[if IE 6]>
  <%= javascript_include_tag 'DD_belatedPNG' %>
  <script>
    DD_belatedPNG.fix('.kx');
  </script>
<![endif]-->

app/views/share/_u_center.html.slim
.right.links
  - if login?
    .login
      .u-center
        = image_tag current_user.avatar.tiny.url, size: '20x20'
        ul.menu
          li: a href="#{new_joke_path}" 发表笑料
          li: a href="#{user_path(current_user)}" 我的主页
          li: a href="#{settings_profile_path}" 资料设置
          li.no-border-bottom: a href="#{logout_path}" data-method="DELETE" 退出登录      
      .welcome #{current_user.login}, 欢迎回来
  - else
    .no-login
      a href="/auth/weibo" 微博登录
      a href="/auth/qq" QQ 
      a |
      a href="#{login_path}" 登录
      a.no-margin-right href="#{signup_path}" 注册  