config/routes.rb
class MobileConstraint
  def self.matches?(request)
    agent_str = request.user_agent.to_s.downcase
    (agent_str =~ Regexp.new(MOBILE_USER_AGENTS)) or request.subdomain == 'm'
  end
end

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # API
  # require 'dispatch'
  # mount Api::Dispatch => '/api'

  get '/jokes/video' => redirect('/')

  concern :sessionable do
    get :signup, to: 'users#new'
    post :signup, to: 'users#create'
    get :login, to: 'sessions#new'
    post :login, to: 'sessions#create'
    delete :logout, to: 'sessions#destroy'
    get :login_state, to: 'sessions#login_state'
  end

  concern :votable do
    post :up_vote
    post :down_vote
  end

  concern :jokeable do
    resources :jokes do
      concerns :votable
      resources :comments, shallow: true do
        concerns :votable
      end

      collection do
        get :hot
        get :shenhuifu
        get :qutu
        get :duanzi
        get :random
        get :search
        get :video
      end
    end
  end

  # 移动站的页面
  constraints(MobileConstraint) do
    scope module: 'mobile', as: :mobile do
      get '/jokes/video' => redirect('/')
      root to: 'jokes#index'
      concerns :jokeable
      concerns :sessionable
      resources :users
      resources :tags, only: [:index, :show]
    end
  end

  # 桌面站
  root 'jokes#index'

  # 第三方登录
  get 'auth/weibo/callback', to: 'auth#weibo_callback', as: :weibo_auth
  get 'auth/qq/callback', to: 'auth#qq_callback', as: :qq_auth

  # 瀑布流的单页
  get :hot, to: 'jokes#recommends', as: :recommends

  # 外链广告代码
  scope 'ad', as: 'ad' do
    get :recommends, to: 'ad#recommends'
    get 'pics', to: 'ad#pics', as: :pics
  end

  concerns :jokeable
  resources :users
  resources :tags, only: [:index, :show]
  concerns :sessionable

  namespace :settings do
    resource :password, only: [:show, :update]
    resource :profile, only: [:show, :update]
  end

  # 管理后台
  namespace :admin do
    root to: 'jokes#index'
    resources :jokes do
      collection do
        get :hot
        get :shenhuifu
        get :qutu
        get :duanzi
      end

      member do
        post :approve
        post :reject
        post :recommend
        post :unrecommend
      end
    end

    resources :tags do
      collection do
        get :search
      end
    end

    resources :users do
      member do
        post :block
        post :unblock
      end
    end
    resources :comments
    resources :websites
    resources :ads
  end
end

app/models/joke.rb
class Joke < ActiveRecord::Base
  include Votable
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  mount_uploaders :photos, PhotoUploader

  belongs_to :user
  has_many :comments, dependent: :destroy, as: :commentable
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :title, uniqueness: true, length: { maximum: 40 }, allow_blank: true
  validates :content, presence: true, if: Proc.new { |joke| joke.title.blank? }
  validates :content, uniqueness: true, if: Proc.new { |joke| joke.photos.blank? && joke.video_url.blank? }
  validate :check_video, on: :create

  def check_video
    if !self.photos.blank? && !self.video_url.blank?
      error.add(:base, '视频和图片只能选其一')
    end

    if !self.video_url.blank? && self.video_cover_url.blank?
      error.add(:video_cover_url, '视频预览图地址不能为空')
    end
  end

  enum status: {
    :pending  => 0,
    :approved => 1,
    :rejected => 2
  }

  scope :without_video, -> {
    where(video_url: [nil, '']).where(video_cover_url: [nil, ''])
  }

  scope :approved, -> {
    without_video.where(status: Joke.statuses[:approved]).preload(:user)
  }

  scope :hot, -> {
    without_video.approved.order('up_votes_count DESC, id DESC')
  }

  scope :qutu, -> {
    without_video.approved.where.not(photos: nil).order('id DESC')
  }

  scope :duanzi, -> {
    without_video.approved.where(photos: nil)
                .where(video_url: [nil, ''])
                .where.not(title: [nil, ''])
                .order('id DESC')
  }

  # 随机推荐的
  scope :recommend, -> (limit = 10) {
    find_by_sql(
      <<-SQL
        select * from jokes where recommended is true and photos is not null order by random() limit #{limit};
      SQL
    )
  }

  # 频道页推荐的
  scope :recommends, -> {
    without_video.where(recommended: true).where.not(photos: nil).order('id DESC')
  }

  after_create :update_hot
  after_touch :update_hot

  before_create do
    self.up_votes_count = rand(1000)
    self.down_votes_count = self.up_votes_count * rand(50) / 100
  end

  def self.random
    # See: http://stackoverflow.com/questions/8674718/best-way-to-select-random-rows-postgresql
    sql = <<-SQL
      select * from jokes where random() < 0.01 limit 1;
    SQL

    find_by_sql(sql).first
  end

  def tag_list
    tags.pluck(:name)
  end

  def tag_list=(tags)
    tags = tags.split(/,|，|\s/).map { |tag| tag.strip }.collect do |tag|
      Tag.find_or_create_by! name: tag
    end

    self.tags = tags
  end

  def tag_with(name)
    if tag_list.include?(name)
      return Tag.find_by(name: name)
    end

    tag = Tag.find_or_create_by!(name: name)
    self.tags << tag
  end

  # See https://gist.github.com/xdite/1391980
  def calculate_hot
    score = (up_votes_count - down_votes_count).abs
    order = Math.log10([score, 1].max)

    if score > 0
      sign = 1
    elsif score < 0
      sign = -1
    else
      sign = 0
    end

    seconds = created_at - DateTime.new(1970,1,1)
    long_num = order + sign * seconds / 45000
    (long_num * 10**7).round.to_f / (10**7)
  end

  def update_hot
    # reload because comments_count has been cache in associations
    # reload
    update_attribute :hot, calculate_hot
  end

  def hot_comment
    Rails.cache.read("joke:#{self.id}:hot_comment")
  end

  def next
    Joke.where("id < ?", id).order("id DESC").first
  end

  def prev
    Joke.where("id > ?", id).order("id ASC").first
  end
end

app/models/legacy/joke.rb
class Legacy::Joke < Legacy::Base
  belongs_to :user
  has_many :comments

  def tags
    Legacy::Tag.joins(:taggings).where('taggings.taggable_id = ?', self.id)
  end

  def picture_url
    "http://static.kaixin100.com/uploads/joke/picture/#{self.id}/#{self.picture}"
  end
end

app/controllers/admin/jokes_controller.rb
class Admin::JokesController < Admin::ApplicationController
  before_action :find_joke, only: [:edit, :update, :approve, :reject, :recommend, :unrecommend, :destroy]

  def index
    @jokes = Joke.preload(:comments, :user).order('created_at DESC')
    @jokes = @jokes.paginate(paginate_params)
  end

  def hot
    @jokes = Joke.hot.paginate(paginate_params)
    render action: :index
  end

  def qutu
    @jokes = Joke.qutu.paginate(paginate_params)
    render action: :index
  end

  def duanzi
    @jokes = Joke.duanzi.paginate(paginate_params)
    render action: :index
  end

  def shenhuifu
    @jokes = Joke.distinct.joins(:comments).where("comments.up_votes_count > 0").order('jokes.created_at DESC')
    @jokes = @jokes.paginate(paginate_params)
    render action: :index
  end

  def new
    @joke = current_user.jokes.new
    @joke.anonymous = true
  end

  def create
    @joke = current_user.jokes.build joke_params    
    @joke.ip = request.remote_ip

    if @joke.save
      redirect_to admin_jokes_path
    else
      render :new
    end    
  end

  def edit
  end

  def update
    if @joke.update_attributes(joke_params)
      redirect_to edit_admin_joke_path(@joke.next)
    else
      render :edit
    end
  end

  def approve
    @joke.approved!
  end

  def reject
    @joke.rejected!
  end

  def recommend
    @joke.update_attribute :recommended, true
  end

  def unrecommend
    @joke.update_attribute :recommended, false
  end

  def destroy
    @joke.destroy rescue nil
    redirect_to :back
  end

  private

  def find_joke
    @joke = Joke.find params[:id]
  end

  def joke_params
    params.require(:joke).permit(:title, :content, :anonymous, :tag_list, :video_url, :video_cover_url, :photos => [])
  end

  def paginate_params
    { page: params[:page], per_page: 10, total_entries: 2000 }
  end  
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  before_action :check_if_block
  before_action :login_required, only: [:new, :create]

  def index
    @jokes = Joke.approved.preload(:comments, :user).order('created_at DESC')
    @jokes = @jokes.paginate(paginate_params)
  end

  def hot
    @jokes = Joke.hot.paginate(paginate_params)
    @page_title = "热门笑话"
    render action: :index
  end

  def recommends
    @records = Joke.recommends.paginate(per_page: 18, page: params[:page], total_entries: 2000)
    @page_title = "热门笑料"
  end

  def qutu
    @jokes = Joke.qutu.paginate(paginate_params)
    @page_title = "趣图"
    render action: :index
  end

  def video
    @jokes = Joke.where.not(video_url: nil).preload(:comments, :user).order('created_at DESC')
    @jokes = @jokes.paginate(paginate_params)
    @page_title = '视频'
    render action: :index
  end

  def duanzi
    @jokes = Joke.duanzi.paginate(paginate_params)
    @page_title = "段子"
    render action: :index
  end

  def shenhuifu
    @jokes = Joke.distinct.joins(:comments).where("comments.up_votes_count > 0").order('jokes.created_at DESC')
    @jokes = @jokes.paginate(paginate_params)
    @page_title = "神回复"
    render action: :index
  end

  def new
    @joke = current_user.jokes.new
    @page_title = "发表笑料"
    @joke.anonymous = true
  end

  def create
    @joke = current_user.jokes.build joke_params
    @joke.ip = request.remote_ip

    if @joke.save
      redirect_to @joke
    else
      render :new
    end
  end

  def show
    @joke = Joke.find params[:id]
    if @joke.rejected?
      render status: 404, file: '/public/404.html', layout: false
      return      
    end

    if !@joke.video_url.blank? or !@joke.video_cover_url.blank?
      redirect_to root_url
      return
    end

    @tags = @joke.tags
    @comments = @joke.comments

    keywords = @tags.pluck(:name).to_a
    @page_title = @joke.title.presence || @joke.content.truncate(30)
    @page_keywords = ([@page_title] + keywords).join(',')

    @page_description = if @joke.title.blank?
      ([@joke.content] + keywords).join(',')
    else
      ([@joke.title, @joke.content] + keywords).join(',')
    end

    set_meta_tags :title => @page_title,
                  :description => @page_description,
                  :keywords => @page_keywords,
                  :site => false
  end

  def up_vote
    @joke = Joke.find params[:joke_id]
    voting = @joke.up_votings.build
    voting.user = current_user
    voting.save

    render text: voting.to_json
  end

  def down_vote
    @joke = Joke.find params[:joke_id]
    voting = @joke.down_votings.build
    voting.user = current_user
    voting.save

    render text: voting.to_json
  end

  def search
    @jokes = Joke.search(
      query: {
        multi_match: {
          query: params[:q].to_s,
          fields: ['title', 'content']
        }
      },

      filter: {
        term: {
          status: 'approved'
        }
      }
    ).paginate(paginate_params).records
  end

  private

  def joke_params
    params.require(:joke).permit(:title, :content, :anonymous, :photos => [])
  end

  def paginate_params
    { page: params[:page], per_page: 10, total_entries: 2000 }
  end
end

app/controllers/mobile/jokes_controller.rb
class Mobile::JokesController < Mobile::ApplicationController
  before_action :login_required, only: [:new, :create]

  def index
    @jokes = Joke.approved.preload(:comments, :user).order('created_at DESC')
    @jokes = @jokes.paginate(paginate_params)
  end

  def hot
    @jokes = Joke.hot.paginate(paginate_params)
    @page_title = "热门笑话"
    render action: :index
  end

  def qutu
    @jokes = Joke.qutu.paginate(paginate_params)
    @page_title = "趣图"
    render action: :index
  end

  def video
    @jokes = Joke.where.not(video_cover_url: nil).not(video_url: nil).preload(:comments, :user).order('created_at DESC')
    @jokes = @jokes.paginate(paginate_params)
    @page_title = '视频'
    render action: :index
  end

  def duanzi
    @jokes = Joke.duanzi.paginate(paginate_params)
    @page_title = "段子"
    render action: :index
  end

  def shenhuifu
    @jokes = Joke.distinct.joins(:comments).where("comments.up_votes_count > 0").order('jokes.created_at DESC')
    @jokes = @jokes.paginate(paginate_params)
    @page_title = "神回复"
    render action: :index
  end

  def random
    @joke = Joke.random || Joke.order('hot DESC').first
    redirect_to joke_path(@joke)
  end

  def show
    @joke = Joke.find params[:id]

    if !@joke.video_url.blank? or !@joke.video_cover_url.blank?
      redirect_to root_url
      return
    end

    @tags = @joke.tags
    @comments = @joke.comments

    keywords = @tags.pluck(:name).to_a
    @page_title = @joke.title.presence || @joke.content
    @page_keywords = ([@page_title] + keywords).join(',')

    @page_description = if @joke.title.blank?
      ([@joke.content] + keywords).join(',')
    else
      ([@joke.title, @joke.content] + keywords).join(',')
    end

    set_meta_tags :title => @page_title,
                  :description => @page_description,
                  :keywords => @page_keywords,
                  :site => false
  end

  def new
    @joke = current_user.jokes.new
    @page_title = "发表笑料"
    @joke.anonymous = true
  end

  def create
    @joke = current_user.jokes.build joke_params
    @joke.ip = request.remote_ip

    if @joke.save
      redirect_to @joke
    else
      render :new
    end
  end

  private

  def paginate_params
    { page: params[:page], per_page: 10, total_entries: 2000 }
  end

  def joke_params
    params.require(:joke).permit(:title, :content, :anonymous, :photos => [])
  end
end

app/views/admin/jokes/_form.html.slim
= form_for @joke, url: url_for([:admin, @joke]), html: { class: 'form-horizontal', multipart: true } do |f|
  = render 'admin/share/form_error', form: f
  .form-group
    label.col-sm-3.control-label 标题(可选)
    .col-sm-9
      = f.text_field :title, class: 'form-control', placeholder: '标题'
  .form-group
    label.col-sm-3.control-label 正文
    .col-sm-9
      = f.text_area :content, class: 'form-control', placeholder: '正文'
  .form-group
    label.col-sm-3.control-label 标签
    .col-sm-9
      = f.text_field :tag_list, class: 'form-control', placeholder: '用逗号或者空格隔开'
  .form-group
    label.col-sm-3.control-label 图片(可多选)
    .col-sm-9
      = f.file_field :photos, class: 'form-control', multiple: true 
      div style="margin-top: 20px;"
        - @joke.photos.each do |photo|
          = image_tag photo.thumb.url
  .form-group
    label.col-sm-3.control-label 视频地址(可选)
    .col-sm-9
      = f.text_field :video_url, class: 'form-control', placeholder: '视频的完整url地址'          
  .form-group
    label.col-sm-3.control-label 视频预览图地址
    .col-sm-9
      = f.text_field :video_cover_url, class: 'form-control', placeholder: '视频预览图完整url地址'
  .form-group
    .col-sm-offset-3.col-sm-9
      .checkbox
        label 
          = f.check_box :anonymous
          span 匿名  
  .form-group
    .col-sm-offset-3.col-sm-9
      button.btn.btn-success type="submit" 保存笑话

app/views/admin/jokes/approve.js.erb
var button = '<a class="btn btn-danger btn-xs" data-method="POST" data-remote="true" href="<%= reject_admin_joke_path(@joke) %>">拒绝</a>';

$("tr.joke-item-<%= @joke.id %>").find('.censorship').empty().append(button);

app/views/admin/jokes/edit.html.slim
.container
  .sub-navbar
    ul.nav.sub-navbar-nav
      li class=('active' if action_name == 'index')
        a href="#{admin_jokes_path}" 列表
      li class=('active' if %w(new create edit update).include?(action_name))
        a href=new_admin_joke_path 新建笑话
  .main
    = render 'form'

app/views/admin/jokes/index.html.slim
.container
  .sub-navbar
    ul.nav.sub-navbar-nav
      li class=('active' if action_name == 'index')
        a href="#{url_for}" 列表
      li class=('active' if action_name == 'new')
        a href=new_admin_joke_path 新建笑话


  .main
    table.table-bordered.table-hover.table-striped
      thead
        tr
          th ID
          th 标题
          th 内容
          th 图片
          th 时间
          th 操作
          th 操作
          th 操作
      tbody
        - @jokes.each do |joke|
          tr class="joke-item-#{joke.id}"
            td
              a href="#{joke_path(joke)}" target="_blank"= joke.id
            td.title= joke.title
            td.body= joke.content.truncate(200)
            td.photos
              - joke.photos.each do |p|
                = image_tag p.thumb.url, width: '60'
            td.time= joke.created_at.strftime('%F %T')
            td.censorship
              - if joke.pending?
                a.btn.btn-success.btn-xs data-method="POST" data-remote=true href="#{approve_admin_joke_path(joke)}" 通过
                a.btn.btn-danger.btn-xs data-method="POST" data-remote=true href="#{reject_admin_joke_path(joke)}" 拒绝  
              - elsif joke.approved?
                a.btn.btn-danger.btn-xs data-method="POST" data-remote=true href="#{reject_admin_joke_path(joke)}" 拒绝
              - else
                a.btn.btn-success.btn-xs data-method="POST" data-remote=true href="#{approve_admin_joke_path(joke)}" 通过           
            td.recommend
              - if joke.recommended?
                a.btn.btn-default.btn-xs data-method="POST" data-remote=true href="#{unrecommend_admin_joke_path(joke)}" 取消推荐
              - else
                a.btn.btn-info.btn-xs data-method="POST" data-remote=true href="#{recommend_admin_joke_path(joke)}" 推荐
            td
              a.btn.btn-default.btn-xs href="#{edit_admin_joke_path(joke)}" 编辑
              a.btn.btn-danger.btn-xs data-method="DELETE" data-confirm="确认删除吗" href="#{admin_joke_path(joke)}" 删除

    = will_paginate @jokes, renderer: BootstrapPagination::Rails

app/views/admin/jokes/new.html.slim
.container
  .sub-navbar
    ul.nav.sub-navbar-nav
      li class=('active' if action_name == 'index')
        a href="#{admin_jokes_path}" 列表
      li class=('active' if %w(new create edit update).include?(action_name))
        a href=new_admin_joke_path 新建笑话
  .main
    = render 'form'

app/views/admin/jokes/recommend.js.erb
var button = '<a class="btn btn-default btn-xs" data-method="POST" data-remote="true" href="<%= unrecommend_admin_joke_path(@joke) %>">取消推荐</a>';

$("tr.joke-item-<%= @joke.id %>").find('.recommend').empty().append(button);

app/views/admin/jokes/reject.js.erb
var button = '<a class="btn btn-success btn-xs" data-method="POST" data-remote="true" href="<%= approve_admin_joke_path(@joke) %>">通过</a>';

$("tr.joke-item-<%= @joke.id %>").find('.censorship').empty().append(button);

app/views/admin/jokes/unrecommend.js.erb
var button = '<a class="btn btn-info btn-xs" data-method="POST" data-remote="true" href="<%= recommend_admin_joke_path(@joke) %>">推荐</a>';

$("tr.joke-item-<%= @joke.id %>").find('.recommend').empty().append(button);