config/routes.rb
class MobileConstraint
  def self.matches?(request)
    agent_str = request.user_agent.to_s.downcase
    (agent_str =~ Regexp.new(MOBILE_USER_AGENTS)) or request.subdomain == 'm'
  end
end

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # API
  # require 'dispatch'
  # mount Api::Dispatch => '/api'

  get '/jokes/video' => redirect('/')

  concern :sessionable do
    get :signup, to: 'users#new'
    post :signup, to: 'users#create'
    get :login, to: 'sessions#new'
    post :login, to: 'sessions#create'
    delete :logout, to: 'sessions#destroy'
    get :login_state, to: 'sessions#login_state'
  end

  concern :votable do
    post :up_vote
    post :down_vote
  end

  concern :jokeable do
    resources :jokes do
      concerns :votable
      resources :comments, shallow: true do
        concerns :votable
      end

      collection do
        get :hot
        get :shenhuifu
        get :qutu
        get :duanzi
        get :random
        get :search
        get :video
      end
    end
  end

  # 移动站的页面
  constraints(MobileConstraint) do
    scope module: 'mobile', as: :mobile do
      get '/jokes/video' => redirect('/')
      root to: 'jokes#index'
      concerns :jokeable
      concerns :sessionable
      resources :users
      resources :tags, only: [:index, :show]
    end
  end

  # 桌面站
  root 'jokes#index'

  # 第三方登录
  get 'auth/weibo/callback', to: 'auth#weibo_callback', as: :weibo_auth
  get 'auth/qq/callback', to: 'auth#qq_callback', as: :qq_auth

  # 瀑布流的单页
  get :hot, to: 'jokes#recommends', as: :recommends

  # 外链广告代码
  scope 'ad', as: 'ad' do
    get :recommends, to: 'ad#recommends'
    get 'pics', to: 'ad#pics', as: :pics
  end

  concerns :jokeable
  resources :users
  resources :tags, only: [:index, :show]
  concerns :sessionable

  namespace :settings do
    resource :password, only: [:show, :update]
    resource :profile, only: [:show, :update]
  end

  # 管理后台
  namespace :admin do
    root to: 'jokes#index'
    resources :jokes do
      collection do
        get :hot
        get :shenhuifu
        get :qutu
        get :duanzi
      end

      member do
        post :approve
        post :reject
        post :recommend
        post :unrecommend
      end
    end

    resources :tags do
      collection do
        get :search
      end
    end

    resources :users do
      member do
        post :block
        post :unblock
      end
    end
    resources :comments
    resources :websites
    resources :ads
  end
end

app/models/legacy/tag.rb
class Legacy::Tag < Legacy::Base
  has_many :taggings
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :jokes, through: :taggings
  validates_presence_of :name
  validates_uniqueness_of :name, on: :create
  validates_uniqueness_of :slug, on: :create

  scope :hot, -> { order('taggings_count DESC').limit(20) }

  def hot?
    taggings_count > 50
  end

  before_create do
    g_slug
  end

  def g_slug
    self.slug = Pinyin.t(self.name, splitter: '')
    
    if Tag.find_by(slug: self.slug)
      self.slug = "#{self.slug}#{rand(50)}"
    end
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::ApplicationController
  before_action :find_tag, only: [:edit, :update]

  def index
    @tags = Tag.order('taggings_count DESC, created_at DESC').paginate(paginate_params)
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to admin_tags_path
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @tag.update_attributes(tag_params)
      redirect_to admin_tags_path
    else
      render action: :edit
    end    
  end

  def search
    q = params[:q]
    @tags = Tag.where("name ~ '#{q}' or seo_title ~ '#{q}' or seo_description ~ '#{q}' or seo_keywords ~ '#{q}'").order('created_at DESC').paginate(paginate_params)
    render :index
  end

  private

  def find_tag
    @tag = Tag.find params[:id]
  end

  def tag_params
    params.require(:tag).permit(:name, :slug, :seo_title, :seo_keywords, :seo_description)
  end

  def paginate_params
    { page: params[:page], per_page: 40, total_entries: 2000 }
  end  
end

app/controllers/mobile/tags_controller.rb
class Mobile::TagsController < Mobile::ApplicationController
  def index
    @tags = Tag.order('created_at ASC')
    @page_title = "热门标签"
  end

  def show
    @tag           = Tag.find_by! slug: params[:id]
    @jokes         = @tag.jokes.preload(:comments, :user).without_video.order('created_at DESC').paginate(page: params[:page], per_page: 10)

    title          = "tag笑话_tag笑话大全_笑话_开心100".gsub!(/tag/, @tag.name)
    keywords       = "tag,tag笑话".gsub!(/tag/, @tag.name)
    description    = ("开心100提供最新tag笑话、tag笑话大全等笑话信息，为您精心选择最经典的tag笑话、最搞笑的tag笑话、最内涵的tag笑话、最有深度的tag笑话大全等tag笑话。").gsub!(/tag/, @tag.name)

    @page_keywords = @tag.seo_keywords.presence || keywords
    @page_title = if @tag.seo_title.blank?
      title
    else
      "#{@tag.name}_#{@tag.seo_title}"
    end
    @page_description = @tag.seo_description.presence || description

    set_meta_tags :title => @page_title,
                  :description => @page_description,
                  :keywords => @page_keywords,
                  :site => false
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :check_if_block
  
  def index
    @tags = Tag.order('created_at ASC')
    @page_title = "热门标签"
  end

  def show
    @tag           = Tag.find_by! slug: params[:id]
    @jokes         = @tag.jokes.preload(:comments, :user).without_video.order('created_at DESC').paginate(page: params[:page], per_page: 10)

    title          = "tag笑话_tag笑话大全_笑话_开心100".gsub!(/tag/, @tag.name)
    keywords       = "tag,tag笑话".gsub!(/tag/, @tag.name)
    description    = ("开心100提供最新tag笑话、tag笑话大全等笑话信息，为您精心选择最经典的tag笑话、最搞笑的tag笑话、最内涵的tag笑话、最有深度的tag笑话大全等tag笑话。").gsub!(/tag/, @tag.name)

    @page_keywords = @tag.seo_keywords.presence || keywords
    @page_title = if @tag.seo_title.blank?
      title
    else
      "#{@tag.name}_#{@tag.seo_title}"
    end
    @page_description = @tag.seo_description.presence || description

    set_meta_tags :title => @page_title,
                  :description => @page_description,
                  :keywords => @page_keywords,
                  :site => false
  end
end

app/views/tags/index.html.slim
.box
  .box-content
    ul.tag-list
      - @tags.each do |tag|
        li
          a class=('active' if tag.hot?) href="#{tag_path(tag.slug)}"= tag.name

app/views/tags/show.html.slim
.left-side
  .box.tag
    .box-header
      h1= @tag.name 
      a.more.text-muted 一共 #{@jokes.count} 个 "#{@tag.name}" 相关笑话
    .box-content= @page_description

  - @jokes.each do |joke|
    .joke-item
      .user
        .avatar
          a href="#{user_path(joke.user)}"
            = image_tag joke.user.avatar.thumb.url
          .nickname
            a href="#{user_path(joke.user)}"= joke.user.login
            p.text-muted.timeago title=joke.created_at
      .content
        = render_joke_title(joke)
        .body
          = simple_format joke.content
          = render_joke_photo joke  
          
        - if joke.hot_comment.present?        
          .comment
            .comment-nav
              span 神回复
            .comment-body
              .avatar.small
                a href="#{user_path(joke.hot_comment.user)}"
                  = image_tag joke.hot_comment.user.avatar.thumb.url
                .nickname
                  a href="#{user_path(joke.hot_comment.user)}"= joke.hot_comment.user.login
                  p.text-muted= joke.hot_comment.body
                a.likes.ding href="javascript:;" data-votable_type="comments" data-votable_id=joke.hot_comment.id data-vote="up_vote"
                  i.kx.kx-up-voted
                  span.text-muted= joke.hot_comment.up_votes_count

      .operation
        .left
          a.ding href="javascript:;" data-votable_type="jokes" data-votable_id=joke.id data-vote="up_vote"
            i.kx.kx-up-voted
            span= joke.up_votes_count
          a.cai href="javascript:;" data-votable_type="jokes" data-votable_id=joke.id data-vote="down_vote"
            i.kx.kx-down-voted
            span= joke.down_votes_count
          a.comment.loadComment href="javascript:;" data-joke_id=joke.id
            i.kx.kx-commented
            span= joke.comments_count
        .right

  = will_paginate @jokes, inner_window: 2

.right-side
  - Ad.right_side_top.each do |ad|
    .box.ad= raw(ad.body)

  .box
    .box-header
      h3 精彩趣图
      a.more href="#{qutu_jokes_path}" 更多
    .box-content
      = render 'jokes/qutu'
  .box
    .box-header
      h3 精彩段子
      a.more href="#{duanzi_jokes_path}" 更多
    .box-content
      = render 'jokes/duanzi'

  .stickAd
    - Ad.right_side_fixed.each do |ad|
      .box.ad= raw(ad.body)